language: php
php:
  - 7.4
  - nigthly

before_install:
- composer require phpunit/phpunit:8.* php-coveralls/php-coveralls:2.*
- composer install --dev
 
script:
- ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
 
after_script:
- php vendor/bin/coveralls -v
